trigger:
  tags:
    include:
    - v*

variables:
  dockerRegistryServiceConnection: 'DockerConnectionService'
  dockerHubNamespace: 'FluffyWork'
  backendImageName: 'todo-backend'
  frontendImageName: 'todo-frontend'

pool:
  name: MyLocalAgents

stages:
- stage: Build
  displayName: 'Test, Version and Build'
  jobs:
  - job: TestAndBuild
    displayName: 'Test, Version, Build and Push'
    steps:

    - checkout: self
      fetchDepth: '0'

    - task: DotNetCoreCLI@2
      displayName: 'Run Backend Tests'
      inputs:
        command: 'test'
        projects: '**/*.sln'

    - task: Npm@1
      displayName: 'Install Frontend Dependencies'
      inputs:
        command: 'install'
        workingDir: 'frontend'

    - task: Npm@1
      displayName: 'Run Frontend Tests'
      inputs:
        command: 'custom'
        workingDir: 'frontend'
        customCommand: 'test -- --watchAll=false'

    - task: DotNetCoreCLI@2
      displayName: 'Install GitVersion Tool'
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global GitVersion.Tool'

    - task: PowerShell@2
      name: 'RunGitVersion'
      displayName: 'Calculate Application Version'
      inputs:
        targetType: 'inline'
        script: |
          # Запускаем GitVersion и сохраняем его вывод в JSON-файл
          dotnet-gitversion /output buildserver /nofetch
          
          # Загружаем переменные, которые создал GitVersion
          $json = Get-Content "gitversion.json" -Raw | ConvertFrom-Json
          $semVer = $json.SemVer
          Write-Host "GitVersion calculated SemVer: $semVer"
          
          # Устанавливаем переменную для использования в следующих шагах
          Write-Host "##vso[task.setvariable variable=GitVersion.SemVer]$semVer"

    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(backendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Backend/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(GitVersion.SemVer)
          latest

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(frontendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: |
          $(GitVersion.SemVer)
          latest