trigger:
  tags:
    include:
    - v*

variables:
  dockerRegistryServiceConnection: 'DockerConnectionService'
  dockerHubNamespace: 'FluffyWork'
  backendImageName: 'todo-backend'
  frontendImageName: 'todo-frontend'

pool:
  name: MyLocalAgents

stages:
- stage: Build
  displayName: 'Build and Push Docker images'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push'
    steps:
    - task: PowerShell@2
      name: SetDockerTag
      displayName: 'Set Docker Tag from Git Tag'
      inputs:
        targetType: 'inline'
        script: |
          $gitTag = "$(Build.SourceBranch)".Split('/')[-1]
          Write-Host "Using Git Tag for Docker image: $gitTag"
          Write-Host "##vso[task.setvariable variable=dockerTag;isOutput=true]$gitTag"

    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(backendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Backend/Dockerfile'
        tags: |
          $(SetDockerTag.dockerTag)
          latest

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(frontendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: |
          $(SetDockerTag.dockerTag)
          latest