trigger:
  tags:
    include:
    - v*

variables:
  dockerRegistryServiceConnection: 'DockerConnectionService'
  dockerHubNamespace: 'FluffyWork'
  backendImageName: 'todo-backend'
  frontendImageName: 'todo-frontend'

pool:
  name: MyLocalAgents

stages:
- stage: Build
  displayName: 'Test, Version and Build'
  jobs:
  - job: TestAndBuild
    displayName: 'Test, Version, Build and Push'
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Run Backend Tests'
      inputs:
        command: 'test'
        projects: '**/Backend.Tests.csproj'

    - task: Npm@1
      displayName: 'Install Frontend Dependencies'
      inputs:
        command: 'install'
        workingDir: 'frontend'

    - task: Npm@1
      displayName: 'Run Frontend Tests'
      inputs:
        command: 'custom'
        workingDir: 'frontend'
        customCommand: 'test -- --watchAll=false'

    - task: GitVersion@5
      displayName: 'Calculate Application Version'
      inputs:
        useConfigFile: false

    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(backendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Backend/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          $(GitVersion.SemVer)
          latest

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: '$(dockerHubNamespace)/$(frontendImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: |
          $(GitVersion.SemVer)
          latest