services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile.local
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: postgres
      DB_PASSWORD: 12345
      ASPNETCORE_URLS: "http://+:5235" 
    ports:
      - "5235:5235"
    networks:
      - app-network

  frontend:
    environment:
    - REACT_APP_API_URL=http://backend:5235/api/openapi/v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3001:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge